server:
  port: 7777
spring:
  application:
    name: ANJU-PRODUCT #服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///anju-product?serverTimezone=GMT%2B8
    username: root
    password: root
#配置mapperxml文件的位置
mybatis-plus:
  mapper-locations: classpath*:cn/itsource/anju/mapper/*Mapper.xml

  
