server:
  port: 9999

spring:
  application:
    name: ANJU-ZUUL

zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: ANJU-PLAT
      path: /plat/**
  prefix: /services