server:
  port: 9999

spring:
  application:
    name: ANJU-ZUUL

zuul:
  ignoredServices: '*' 
  routes:
    plat:
      serviceId: ANJU-PLAT
      path: /plat/**
    product:
      serviceId: ANJU-PRODUCT
      path: /product/**
    common:
      serviceId: ANJU-COMMON
      path: /common/**
  prefix: /services
